### ISSUE TITLE
Code expects __ILP32__/__LP64__ to be defined, missing on ARM

### ISSUE THREAD

**Issue by jian2x** [intel/cartwheel-ffmpeg#215]
ILP32 is not defined on 32bit ARM (although it is an ILP32 arch):
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106930

The following code fails to build:
https://github.com/oneapi-src/oneVPL/blob/master/api/vpl/mfxdefs.h#L62-L76

One workaround is to add -D__ILP32__ to CXXFLAGS.

**Comment by jian2x** [comment]
link: https://github.com/oneapi-src/oneVPL/issues/70

**Comment by xhaihao** [comment]
No FFmpeg related.
