### ISSUE TITLE
ICQ for AV1 not working

### ISSUE THREAD

**Issue by jian2x** [intel/cartwheel-ffmpeg#219]
Reference: https://github.com/oneapi-src/oneVPL/issues/79

@oviano helped me find this issue, and can explain it better than I can...

Getting this error while using ICQ:

Error allocating the output packet rate=xxxxkbits/s speed = x.xx Error submitting video frame to the encoder

It looks like neither param.mfx.BufferSizeInKB or param.mfx.BRCParamMultiplier in qsv_retrieve_enc_av1_params get set when the codec is AV1, and are thus still zero

**Comment by jian2x** [comment]
Issue tracking link : https://github.com/oneapi-src/oneVPL/issues/82

**Comment by xhaihao** [comment]
driver issue: https://github.com/intel/media-driver/issues/1597
