### ISSUE TITLE
How to select different devices with MFXLoad and MFXCreateSession API

### ISSUE THREAD

**Issue by jian2x** [intel/cartwheel-ffmpeg#220]
I have both an Intel Arc as well as an Intel UHD 770 iGPU, and would like to be able to select which hardware to use.
I could not find what is the way to select the hardware adapter with the newer Load and CreateSession method. The documentation only mention it with the legacy API.

Could a code sample be provided that demonstrates this functionality?

**Comment by xhaihao** [comment]
oneVPL question.
