### ISSUE TITLE
unsupported (-3) with int_ref_type=3

### ISSUE THREAD

**Issue by alatteri** [intel/cartwheel-ffmpeg#229]
Hello,

I'm testing hevc_qsv with NUC12 and an app that relies on libavcodec.

`int_ref_type=3` errors with
[lavc hevc_qsv @ 0x7f661c2044c0] Error querying encoder params: unsupported (-3)

but `int_ref_type=-1/0/1/2` work fine.

In qsvenc_hevc.c. the valid range is 0-3.   So I'm wondering if everything just got shifted down 1 value?

```
        { "none",     NULL, 0, AV_OPT_TYPE_CONST, { .i64 = 0 }, .flags = VE, "int_ref_type" },
        { "vertical", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = 1 }, .flags = VE, "int_ref_type" },
        { "horizontal", NULL, 0, AV_OPT_TYPE_CONST, { .i64 = 2 }, .flags = VE, "int_ref_type" },
        { "slice"     , NULL, 0, AV_OPT_TYPE_CONST, { .i64 = 3 }, .flags = VE, "int_ref_type" }, 
```

**Comment by xuguangxin** [comment]
thank you @alatteri  for report this. @wenbinc-Bin could you help check?
thank you

**Comment by wenbinc-Bin** [comment]
Hi @alatteri,  it is not shifted. Setting -1 means do not set int_ref_type which equals to setting 0. "slice refresh" has not been supported by VPL on h265 yet.

**Comment by alatteri** [comment]
But if I set 0 I definitely see a vertical refresh, if I set 1 is see a horizontal refresh, and 2 kind of a diamond shape.   So that setting is doing something.

**Comment by wenbinc-Bin** [comment]
That is wired.
my command (vertical):
ffmpeg -v verbose -i input.264 -c:v hevc_qsv -int_ref_type 1 -int_ref_cycle_size 4 output.265
and I get frame like these:
![Screenshot from 2023-02-14 10-56-39](https://user-images.githubusercontent.com/39874721/218628048-5ddd7481-1577-402c-b2c1-e4cf6e88106e.png)
![Screenshot from 2023-02-14 10-56-43](https://user-images.githubusercontent.com/39874721/218628060-57d115ec-d56b-444c-b030-28a4daa3d85b.png)
![Screenshot from 2023-02-14 10-56-47](https://user-images.githubusercontent.com/39874721/218628251-29f05049-50fa-49d9-80df-09be05cc836e.png)
![Screenshot from 2023-02-14 10-56-50](https://user-images.githubusercontent.com/39874721/218628267-d448da2a-98e5-4787-82a3-eaf273aecd91.png)



If I change to horizontal, I get frames like these:
ffmpeg -v verbose -i input.264 -c:v hevc_qsv -int_ref_type 2 -int_ref_cycle_size 4 output.265
![Screenshot from 2023-02-14 10-57-16](https://user-images.githubusercontent.com/39874721/218628385-ef7b3271-77f3-4d90-b000-c0aac567c2cc.png)
![Screenshot from 2023-02-14 10-57-19](https://user-images.githubusercontent.com/39874721/218628225-29cfa587-7715-4387-aea0-1712996e57dd.png)
![Screenshot from 2023-02-14 10-57-22](https://user-images.githubusercontent.com/39874721/218628284-849614a0-095f-4ffa-8882-20d547b79ac6.png)
![Screenshot from 2023-02-14 10-57-24](https://user-images.githubusercontent.com/39874721/218628292-1c00f7a7-26ca-430f-9374-d05fcdabce69.png)

If I set int_ref_type to 0, the frames I get:
![Screenshot from 2023-02-14 11-04-19](https://user-images.githubusercontent.com/39874721/218628614-b9a692b9-17ca-45b7-a3cc-5568a15d297d.png)

**Comment by wenbinc-Bin** [comment]
If these are different with what you observed, can you please provide your command and paste the terminal log. Please add option "-v verbose" when you run command which lets ffmpeg print more information.

If it is possible, can you also provide your output frame with MB infomation and let's compare the results.
