### ISSUE TITLE
[VAAPI AV1 Encode] tx_mode_support mask should be considered when setting set tx_mode

### ISSUE THREAD

**Issue by sivileri** [intel/cartwheel-ffmpeg#241]
@feiwan1 I noticed the vaapi av1 encoder is using [VAConfigAttribValEncAV1Ext2](https://github.com/intel/libva/blob/master/va/va_enc_av1.h#L193) to set the tx_mode to be used in [VAEncPictureParameterBufferAV1](https://github.com/intel/libva/blob/master/va/va_enc_av1.h#L780), but I think there's may be slight semantic mismatch with the VAAPI definition in `va_enc_av1.h`, as it should parse the bitmask and choose only one of the supported tx modes instead of assigning it.

https://github.com/intel/cartwheel-ffmpeg/blob/master/patches/0071-lavc-vaapi-support-av1-encode.patch#L1507

<img width="391" alt="image" src="https://user-images.githubusercontent.com/82116493/228067008-c5d74b2b-ce55-45d4-b525-a409260f23eb.png">

**Comment by feiwan1** [comment]
Thanks @sivileri to report this. I am cleanning up AV1e code recently to prepare upstream it, I will fix this together.

**Comment by feiwan1** [comment]
Fixed https://github.com/intel-media-ci/ffmpeg/pull/648

**Comment by feiwan1** [comment]
The fix also merged in cartwheel. Close this issue.
