### ISSUE TITLE
[Feature Request] Compatibility

### ISSUE THREAD

**Issue by thx4ever** [intel/cartwheel-ffmpeg#246]
Hi, its possible to add compatibility with Media Server Studio plugins again? I can see load_plugins options but it doesnt work without intel GPU since ffmpeg version 4.5 in software mode using libmfxsw64.dll and 2fca99749fdb49aeb121a5b63ef568f7 (mfxplugin64_hevce_sw.dll), why with ffmpeg 4.5 it works but in this newer ffmpeg versions 5 or 6 it doesnt?
Until now i can only use software mode wihthout intel GPU, but i have plans to buy Intel ARC A380 graphics card
My build have libmfx and libvpl
My ffmpeg command line options:

ffmpeg -v verbose -hide_banner -i C:\Users\Administrator\Desktop\Source2.264 -c:v hevc_qsv -pix_fmt nv12 -load_plugin hevc_sw -profile:v main -preset:v veryslow -bsf:v hevc_metadata=transfer_characteristics=1:colour_primaries=1:video_full_range_flag=0:matrix_coefficients=1 -b:v 2500k C:\Users\Administrator\Desktop\teste.hevc

This message i get when try to use ffmpeg above version 4.5
[hevc_qsv @ 000001AA94A52A00] Error initializing a MFX session: unsupported (-3)
[vost#0:0/hevc_qsv @ 000001AA94A48080] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.

Regards

**Comment by thx4ever** [comment]
I have now enabled --enable libmfx but it always show error -3, its possible to add support to use software mode libmfxsw64.dll use?

**Comment by xhaihao** [comment]
@thx4ever  There isn't a tag for version 4.5 in http://git.videolan.org/?p=ffmpeg.git;a=tags, are you using an official version ?

**Comment by xhaihao** [comment]
@nyanmisaka thanks for the comment.

@thx4ever  I'm sorry I don't have the environment to try libmfxsw64.dll, could you help to try FFmpeg 5.0 (which doesn't support oneVPL, we shouldn't change too much for QSV) ?

**Comment by thx4ever** [comment]
Yes i did test it it show error -3 because i dont have a Intel GFX or GPU installed, but it works fine without it on ffmpeg 4.5 old version, since i dont have a intel GPU it doesnt work in old version ffmpeg 4.5 it doesnt matter it load libmfxsw64.dll and works

**Comment by xhaihao** [comment]
@thx4ever could you try https://github.com/intel-media-ci/ffmpeg/pull/649  ?

**Comment by thx4ever** [comment]
OK i will try and report back

**Comment by thx4ever** [comment]
Doesn't work
[hevc_qsv @ 00000262DDC3CC00] Encoder: input is system memory surface
[hevc_qsv @ 00000262DDC3CC00] Use Intel(R) Media SDK to create MFX session, the required implementation version is 1.1
[hevc_qsv @ 00000262DDC3CC00] Error initializing a MFX session: unsupported (-3)
[vost#0:0/hevc_qsv @ 00000262DD38BA80] Error while opening encoder - maybe incorrect parameters such as bit_rate, rate, width or height.
libmfxsw64.dll and plugins in current directory of ffmpeg.exe
