### ISSUE TITLE
h264_qsv QVBR does not respect -maxrate parameter

### ISSUE THREAD

**Issue by BlakeB415** [intel/cartwheel-ffmpeg#258]
I found that the QVBR mode of h264_qsv ignores the ``-maxrate`` setting resulting in very low bitrates.

I did a little searching and I found this on the ffmpeg mailing list from 2020. I tried the patch and it works as intended. 
https://www.mail-archive.com/ffmpeg-devel@ffmpeg.org/msg108763.html

**Comment by xhaihao** [comment]
What's your FFmpeg version ? Both mfx.TargetKbps and mfx.MaxKbps  are set (see https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/qsvenc.c#L884-L892) in qsvenc.c. Note QVBR is one of VBR, according to https://github.com/FFmpeg/FFmpeg/blob/master/doc/encoders.texi#L3254-L3256, user should set  maxbit rate @option{maxrate} and average bit rate @option{b}, and make sure maxrate > average bit rate.

**Comment by BlakeB415** [comment]
> What's your FFmpeg version ? Both mfx.TargetKbps and mfx.MaxKbps are set (see https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/qsvenc.c#L884-L892) in qsvenc.c. Note QVBR is one of VBR, according to https://github.com/FFmpeg/FFmpeg/blob/master/doc/encoders.texi#L3254-L3256, user should set maxbit rate @option{maxrate} and average bit rate @option{b}, and make sure maxrate > average bit rate.

QVBR should only require -global_quality and -maxrate to be set. Specifying -b:v puts it into normal VBR mode which doesn't use the ICQ scale.

**Comment by xhaihao** [comment]
Please refer to the description about MFX_RATECONTROL_QVBR in https://github.com/Intel-Media-SDK/MediaSDK/blob/master/doc/mediasdk-man.md#RateControlMethod

MFX_RATECONTROL_QVBR | Use the variable bitrate control algorithm with constant quality.  This algorithm trying to achieve the target subjective quality with the  minimum number of bits, while the bitrate constraint and HRD compliancy  are satisfied. **It uses the same set of parameters as VBR** and quality  factor specified by mfxExtCodingOption3::QVBRQuality.

**Comment by BlakeB415** [comment]
> MFX_RATECONTROL_QVBR | Use the variable bitrate control algorithm with constant quality. This algorithm trying to achieve the target subjective quality with the minimum number of bits, while the bitrate constraint and HRD compliancy are satisfied. **It uses the same set of parameters as VBR** and quality factor specified by mfxExtCodingOption3::QVBRQuality.

I see. What is the suggested offset between the targetkbps and the maxkbps? Can the max kbps just be +1 of the target rate or should it be more significant? 

Thank you again!

**Comment by xhaihao** [comment]
> I see. What is the suggested offset between the TargetKbps and the MaxKbps for this rc mode? Can the MaxKbps just be +1 of the TargetKbps or should it be more significant?

Yes, user can set MaxKbps to  TargetKbps + 1

**Comment by BlakeB415** [comment]
Since this is intended behavior, I'll close this issue.
