### ISSUE TITLE
Call `av_hwdevice_ctx_create` failed in FFmpeg master with libvpl.

### ISSUE THREAD

**Issue by albyho** [intel/cartwheel-ffmpeg#260]
``` sh
[AVHWDeviceContext @ 000001d97cd6cb40] Error creating a MFX session: -9.
```

FFmpeg 4.3.1 is OK.

GPU: Intel(R) Iris(TM) Pro Graphics 5200
CPU: Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz

Is it similar to this issue?
[https://github.com/intel/cartwheel-ffmpeg/issues/246](https://github.com/intel/cartwheel-ffmpeg/issues/246)

**Comment by xhaihao** [comment]
No, it isn't similar to #246.  oneVPL-gpu-runtime (libmfx-gen.so) doesn't support legacy platforms. You should install mediasdk-runtime ( libmfxhw64.so) even if FFmpeg is linked against libvpl.

**Comment by albyho** [comment]
Tks.
